EUROPE = {
  'Kosovo',
  'Azerbaijan',
  'Belarus',
  'Luxembourg',
  'Vatican City',
  'Liechtenstein',
  'Greece',
  'Malta',
  'Russia',
  'France',
  'North Macedonia',
  'San Marino',
  'Ukraine',
  'Germany',
  'Moldova',
  'Denmark',
  'Italy',
  'Romania',
  'Monaco',
  'Croatia',
  'Poland',
  'Cyprus',
  'Ireland',
  'Kazakhstan',
  'Iceland',
  'Latvia',
  'Albania',
  'Netherlands',
  'Spain',
  'Montenegro',
  'Armenia',
  'Bosnia and Herzegovina',
  'Estonia',
  'Switzerland',
  'Georgia',
  'Lithuania',
  'Serbia',
  'Sweden',
  'United Kingdom',
  'Norway',
  'Bulgaria',
  'Slovakia',
  'Portugal',
  'Finland',
  'Andorra',
  'Czechia',
  'Austria',
  'Turkey',
  'Belgium',
  'Hungary',
  'Slovenia'
}
ASIA = {
  'Iraq',
  'Philippines',
  'Singapore',
  'Kazakhstan',
  'Mongolia',
  'Cyprus',
  'Uzbekistan',
  'Myanmar ',
  'Lebanon',
  'Pakistan',
  'Laos',
  'Nepal',
  'China',
  'North Korea',
  'Qatar',
  'United Arab Emirates',
  'Jordan',
  'Japan',
  'Brunei',
  'Bahrain',
  'Syria',
  'Tajikistan',
  'Turkmenistan',
  'Georgia',
  'Bangladesh',
  'Maldives',
  'Palestine',
  'Russia',
  'Turkey',
  'Bhutan',
  'Taiwan',
  'Indonesia',
  'South Korea',
  'Armenia',
  'Kuwait',
  'Cambodia',
  'Iran',
  'Oman',
  'India',
  'Kyrgyzstan',
  'Saudi Arabia',
  'Afghanistan',
  'Sri Lanka',
  'Yemen',
  'Azerbaijan',
  'Malaysia',
  'Timor-Leste',
  'Thailand',
  'Israel',
  'Vietnam'
}
AFRICA = {
  'South Sudan',
  'Ethiopia',
  'Somalia',
  'Namibia',
  'South Africa',
  'Kenya',
  'Morocco',
  'Gambia',
  'Comoros',
  'Central African Republic',
  'Burundi',
  'Malawi',
  'Gabon',
  'Lesotho',
  'Sudan',
  'Equatorial Guinea',
  'Rwanda',
  'Eswatini',
  'Senegal',
  'Seychelles',
  'Algeria',
  'Togo',
  'Zimbabwe',
  'Egypt',
  'Eritrea',
  'Uganda',
  'Liberia',
  'Burkina Faso',
  'Guinea',
  'Mali',
  'Congo',
  'Tanzania',
  'Cabo Verde',
  'Benin',
  'Ghana',
  'Guinea-Bissau',
  'Mauritania',
  'Nigeria',
  'Sao Tome and Principe',
  'Sierra Leone',
  'Djibouti',
  'Angola',
  'Mozambique',
  'Mauritius',
  'Chad',
  'Madagascar',
  'Niger',
  'Cameroon',
  "Cote d'Ivoire",
  'Libya',
  'Zambia',
  'Botswana',
  'Tunisia'
}
NORTH_AMERICA = {
  'Panama',
  'Cuba',
  'Saint Kitts and Nevis',
  'Mexico',
  'Antigua and Barbuda',
  'Costa Rica',
  'Barbados',
  'Honduras',
  'Saint Lucia',
  'United States of America',
  'USA',
  'Haiti',
  'Bahamas',
  'Nicaragua',
  'Belize',
  'Dominican Republic',
  'Saint Vincent and the Grenadines',
  'Jamaica',
  'Guatemala',
  'Dominica',
  'Trinidad and Tobago',
  'Canada',
  'El Salvador',
  'Grenada'
}
SOUTH_AMERICA = {
  'Peru',
  'Colombia',
  'Ecuador',
  'Suriname',
  'Chile',
  'Venezuela',
  'Argentina',
  'Uruguay',
  'Bolivia',
  'Guyana',
  'Paraguay',
  'Brazil'
}
AUSTRALIA_OCEANIA = {
  'Wallis and Futuna',
  'Guam',
  'Tuvalu',
  'New Caledonia',
  'French Polynesia',
  'Australia',
  'Northern Mariana Islands',
  'Kiribati',
  'Papua New Guinea',
  'Micronesia',
  'Niue',
  'Tokelau',
  'Cook Islands',
  'Vanuatu',
  'Palau',
  'New Zealand',
  'Norfolk Island',
  'Fiji',
  'Tonga',
  'Wake Island',
  'Solomon Islands',
  'Samoa',
  'Pitcairn Islands',
  'American Samoa',
  'Nauru',
  'Marshall Islands'
}

ALL_CONTINENTS = {'EUROPE': EUROPE,
  'ASIA': ASIA,
  'NORTH_AMERICA': NORTH_AMERICA,
  'SOUTH_AMERICA': SOUTH_AMERICA,
  'AUSTRALIA_OCEANIA': AUSTRALIA_OCEANIA,
  'AFRICA': AFRICA
}
ALL_COUNTRIES = {}

for continent_name, countries_set in ALL_CONTINENTS.items():
    for country in countries_set:
        ALL_COUNTRIES[country] = continent_name
